apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ujfkys7jo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ujfkys7jo-go 
  name: ujfkys7jo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ujfkys7jo-go 
